version: "3"
services:
  web:
    container_name: battle-cats-rolls-web
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      RAILS_ENV: development
      RAKE_ENV: development
    ports:
      - 80:9090
